### ISSUE TITLE
Where is RPB and RGB of EDSA block in the code?

### ISSUE THREAD

**Issue by SchuckLee** [Peterande/GET-Group-Event-Transformer#1]
Awesome work!
I'm a rookie in deep learning, and I can't find the relative position bias(RPB) in your code. Could you please point out the position of RPB and RGB in the code? Thanks a lot!

**Comment by Peterande** [comment]
Thanks for the praise! 
RPB and RGB are written in the GET.py as relative_position_bias and relative_position_bias_i.

**Comment by Peterande** [comment]
Thanks for the praise! 
RPB and RGB are written in the GET.py as relative_position_bias and relative_position_bias_i.

**Comment by SchuckLee** [comment]
Hey, there's another question confused me. In the paper, it is written that "We first discretize the time of asynchronous events to K intervals..." I would like to know how to extract frames. If K=2 is set, shouldn't an event be extracted at the beginning, middle, and end each frame? But here are 3 frames, which does not meet the formula of G=2 * K.If there are any errors in my understanding, please feel free to point them out.

**Comment by Peterande** [comment]
“If K=2 is set, shouldn't an event be extracted at the beginning, middle, and end each frame? But here are 3 frames” 
I don't quite understand this sentence; please refer to line 19 of event_based/event_token.py, where self.time_div is equal to K.

**Comment by SchuckLee** [comment]
Sorry, I didn't express clearly. But now I have figured it out. Thanks!
