### ISSUE TITLE
reported obj detection results: mAP vs AP50

### ISSUE THREAD

**Issue by magehrig** [Peterande/GET-Group-Event-Transformer#2]
HI @Peterande 

In table 3 and 4 of the paper you write "mAP" in the top row, but in the caption, you mention that you report "AP50".
Could you clarify which metric you used?

E.g. RVT reports the mAP, not AP50.

--- update ---
After re-reading the tables' captions I realized that probably only the **FS** paper results are in AP50 and the rest should be mAP. Can you confirm?

**Comment by Peterande** [comment]
Yes, only the results marked with ∗ are in "AP50". Our results are "mAP" obtained using your evaluation code in RVT. Thank you again for your outstanding work.
