### ISSUE TITLE
pretrain model

### ISSUE THREAD

**Issue by QiWang233** [Peterande/GET-Group-Event-Transformer#5]
I wonder what's your pretrain model on action recognition target? thank you !

**Comment by Peterande** [comment]
Here~ 👇🏻👇🏻👇🏻
https://github.com/Peterande/GET-Group-Event-Transformer/tree/master_with_checkpoints/checkpoints

**Comment by QiWang233** [comment]
I guess this should be a model you have trained rather than a pre-training model, right?

**Comment by QiWang233** [comment]
I guess this should be a model you have trained rather than a pre-training model, or do you start training from scratch?

**Comment by Peterande** [comment]
All models are trained from scratch.

**Comment by QiWang233** [comment]
thanks！

**Comment by Peterande** [comment]
My pleasure.
